### ISSUE TITLE
Hide icon in Activity Bar when README.md is closed

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#1]

**Comment by rongxin-liu** [comment]
Don't think we can achieve this behavior. The icon is added when the extension is activated, and only the user can hide it. There is also no VS Code API to deactivate the extension.

**Comment by rongxin-liu** [comment]
In fact this is the same thing we had been trying to do:
https://github.com/cs50/code.cs50.io/issues/34
https://github.com/cs50/code.cs50.io/issues/35
https://github.com/cs50/code.cs50.io/issues/36

**Comment by dmalan** [comment]
> In fact this is the same thing we had been trying to do:

I think the difference here is those aren't our extensions? I think there's, at least, a way to hide/show the activity bar's icon via a `when` clause or such in `package.json`, in which case maybe there's a similar mechanism in code, a la our `hasLayout` key?

**Comment by rongxin-liu** [comment]
No I'm afraid, not for view container.

**Comment by dmalan** [comment]
Actually, should be possible using `enablement`! If you install latest release of https://marketplace.visualstudio.com/items?itemName=lostintangent.workspace-layout (not the version on `main`), you'll see that the README has a close icon (X). When clicked, it closes, and the activity bar icon disappears.

https://github.com/lostintangent/workspace-layout/blob/9e245a666b4e19b3a98173cfe415f5dd08604b6f/package.json#L30-L35

https://github.com/lostintangent/workspace-layout/blob/9e245a666b4e19b3a98173cfe415f5dd08604b6f/src/layout.ts#L77-L79

**Comment by rongxin-liu** [comment]
Interesting, thanks!
