### ISSUE TITLE
Does VS Code have default CSS for styling buttons in a manner consistent with VS Code theme?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#14]
Without Bootstrap, `<button>` renders as:

<img width="124" alt="Screen Shot 2022-09-09 at 8 41 35 PM" src="https://user-images.githubusercontent.com/788678/189461941-5c5f3f63-21a8-475f-99f6-6109461e7903.png">

Is there a way to coerce it to render like a button consistent with VS Code's own UI, using some default CSS (not our own)?

**Comment by rongxin-liu** [comment]
This is the CSS style sheet I could find from their official example repo:
https://github.com/microsoft/vscode-extension-samples/blob/main/webview-view-sample/media/vscode.css

**Comment by dmalan** [comment]
Able to screenshot what those buttons would look like?

**Comment by rongxin-liu** [comment]
Looks like these:
<img width="317" alt="Screen Shot 2022-09-10 at 15 48 32" src="https://user-images.githubusercontent.com/10591665/189499544-fc6c9d41-aeb1-4529-8d73-30324ae1b2bd.png">

**Comment by dmalan** [comment]
Is `--vscode-button-foreground` always green by default? (Is that set in each theme?)

**Comment by rongxin-liu** [comment]
Nope, it would adjust based on theme:

<img width="955" alt="Screen Shot 2022-09-10 at 15 51 32" src="https://user-images.githubusercontent.com/10591665/189499701-7bdcd4a4-62ee-4955-adf8-46622e41455d.png">
<img width="545" alt="Screen Shot 2022-09-10 at 15 51 40" src="https://user-images.githubusercontent.com/10591665/189499704-19f37ea5-ca0a-4c67-83e6-0d834781a32f.png">
<img width="557" alt="Screen Shot 2022-09-10 at 15 51 47" src="https://user-images.githubusercontent.com/10591665/189499705-eaf7c04d-a17e-4fbc-9713-2e5234c6e0f6.png">
<img width="599" alt="Screen Shot 2022-09-10 at 15 51 55" src="https://user-images.githubusercontent.com/10591665/189499706-c9e125cb-e826-4552-94b9-dcfe36ebde35.png">
<img width="514" alt="Screen Shot 2022-09-10 at 15 51 52" src="https://user-images.githubusercontent.com/10591665/189499707-2805b17a-86da-4998-8d96-3d1a22e3fa90.png">

**Comment by dmalan** [comment]
Sounds good then!
