### ISSUE TITLE
Does VS Code's API support double-clicking on folders in Explorer, such that that could also open a lab?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#18]

**Comment by rongxin-liu** [comment]
Not seeing such API I'm afraid.

Double-clicking on folders would just "open and close" the folder. For the proposed implementation to work, it might only be possible if there is a setting to first change the folder open mode to "doubleClick", then there is an API somehow allow "doubleClick" event listening on folder.

**Comment by rongxin-liu** [comment]
Somewhat related issue:
https://github.com/Microsoft/vscode/issues/39601#issuecomment-398751109

**Comment by dmalan** [comment]
Okay, no problem. Perhaps a visual indicator alone, like a custom icon just for folders with `README.md` files, would help, https://github.com/cs50/lab50.vsix/issues/19?

Or if not possible for folders, just a custom icon for `README.md` files? Though not sure how helpful that will prove!
