### ISSUE TITLE
Does VS Code's API support adding an icon next to folders's names in Explorer (if folder contains `.cs50.yml`), such that that clicking those could also open a lab, or just visually indicate it's a supported lab folder?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#19]
A la an icon theme, but just one special icon for lab folders?

https://code.visualstudio.com/blogs/2016/09/08/icon-themes

**Comment by rongxin-liu** [comment]
Looking at [this documentation](https://code.visualstudio.com/api/extension-guides/file-icon-theme#file-association), the closest thing we could do is to prefix a name (e.g., "cs50lab_*") for our problem set folder and we could get a customized icon for that folder.

**Comment by dmalan** [comment]
Ah, okay, no need then!
