### ISSUE TITLE
Does VS Code come with default CSS for pre/code blocks so that code blocks could potentially have some sort of rectangle or background color around them, without resorting to custom CSS?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#22]
<img width="568" alt="Screen Shot 2022-09-09 at 9 01 19 PM" src="https://user-images.githubusercontent.com/788678/189462642-99bd4ff0-53f9-4543-82bb-080c7033e9d9.png">

**Comment by rongxin-liu** [comment]
https://github.com/cs50/lab50.vsix/issues/14

**Comment by rongxin-liu** [comment]
code blocks now have vscode style background (using editor color scheme):

<img width="571" alt="Screen Shot 2022-09-10 at 21 21 23" src="https://user-images.githubusercontent.com/10591665/189507635-1a4e0e09-25a0-43bd-9a79-450483f64f0d.png">
<img width="586" alt="Screen Shot 2022-09-10 at 21 21 19" src="https://user-images.githubusercontent.com/10591665/189507636-ace235af-d19e-4f32-9dbc-0d8ef9c9a978.png">

**Comment by dmalan** [comment]
Would it be cleaner just to include all of https://github.com/microsoft/vscode-extension-samples/blob/main/webview-view-sample/media/vscode.css after all, rather than maintain excerpts in our `lab50.css`?

**Comment by rongxin-liu** [comment]
No, that's only a demo of showing how to use vscode's theme color. It doesn't even cover `<code>` `<pre>` tag styles and such.

**Comment by rongxin-liu** [comment]
So we only include vscode style that we need in our `lab50.css`, I think that's cleaner actually. I also made some tweaks to the button style because the one shown in the demo wasn't looking good.
