### ISSUE TITLE
Can VS Code's console height be maximized programmatically (to fill editor area), or only via mouse click?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#24]

**Comment by rongxin-liu** [comment]
You mean the built-in chromium console?
<img width="837" alt="Screen Shot 2022-09-09 at 21 50 00" src="https://user-images.githubusercontent.com/10591665/189464749-3e0fdf0a-2aa4-456d-830d-afba833411c0.png">

**Comment by dmalan** [comment]
No no, VS Code's terminal window (which lives in VS Code's "console" area).

**Comment by rongxin-liu** [comment]
No, it cannot be controlled programmatically. And I find out that only if the panel alignment is in center mode will you find the "Maximize Panel Size" option in the terminal.

![Screen Shot 2022-09-13 at 10 55 13](https://user-images.githubusercontent.com/10591665/189935649-74616bc3-adc0-419f-bbc1-d3813f0f4e4c.png)
