### ISSUE TITLE
Implement {% local %} tag in liquid, adding FontAwesome 5 CSS URL to HMTL for icons

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#26]

**Comment by rongxin-liu** [comment]
What does this tag do?

**Comment by dmalan** [comment]
Ah this one!

https://cs50.readthedocs.io/themes/jekyll/#local

**Comment by dmalan** [comment]
Perhaps just using these defaults, no need for customization, using https://moment.github.io/luxon/? 

https://github.com/cs50/jekyll-theme-cs50/blob/develop/lib/jekyll-theme-cs50/constants.rb#L13-L20

Current implementation is in https://github.com/cs50/jekyll-theme-cs50/blob/develop/assets/jekyll-theme-cs50.js#L170-L267, though parsing of the YYYY-MM-DD HH:MM datetimes is currently done in Ruby, but https://moment.github.io/luxon/#/parsing?id=fromformat should do the trick in JS?

**Comment by rongxin-liu** [comment]
It occurs to me that on Codespace local time would be `UTC`:

![Screen Shot 2022-09-10 at 18 29 23](https://user-images.githubusercontent.com/10591665/189503973-ea8b0ea7-339f-4cda-b7ea-d59fc7720d76.png)

Should we enforce EST/EDT timezone on Codespace or what do think would be best to approach this?

**Comment by dmalan** [comment]
Good catch. I can add some code to autodetect and inject into `.devcontainer.json`, which will help with that. No rush on the `local` tag in the meantime!

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/ce9b9eac5216b681845761c95051b2e0992f3830](https://github.com/cs50/lab50.vsix/commit/ce9b9eac5216b681845761c95051b2e0992f3830)
