### ISSUE TITLE
If user clicks on `README.md` itself, before it opens in editor, prompt user whether they want to open it in CS50 Lab

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#27]
Per https://github.com/cs50/lab50.vsix/issues/25, if we indeed assume default values of:

```
---
files: []
port: 8080
window:
  - terminal
---
# README
...
```

then it isn't strictly necessary for some labs to have any YAML keys at all, assuming the above are acceptable for some lab. Rather than prompt users whether they want to open _any_ `README.md` in CS50 Lab, perhaps it'd be best to require that any lab at least have empty YAML front matter, just like https://jekyllrb.com/docs/front-matter/. I.e.:

```
---
---
# README
...
```

Because `README.md` files are so common, that would significantly reduce the probability that a user is prompted to open as a lab a file that isn't intended to be a lab.

Note that our Jekyll sites don't require (empty) YAML front matter only because we're using https://github.com/benbalter/jekyll-optional-front-matter.

**Comment by dmalan** [comment]
Is it possible for context menus only to show for certain filenames? If so, might be compelling to add this? If not even possible, can close!

**Comment by dmalan** [comment]
@rongxin-liu might https://code.visualstudio.com/api/references/vscode-api#window.registerCustomEditorProvider allow us to intercept the user opening a `.md` file and then prompt them whether they want to open it in CS50 Lab or in the default editor?

**Comment by rongxin-liu** [comment]
Yes, this is doable. That's how phpliteadmin is implemented.

**Comment by rongxin-liu** [comment]
If we do this, any time user click on an .md file would go through our extension first.

**Comment by dmalan** [comment]
Seems reasonable in our context? Worst case, can always add a setting via which users could suppress such?
