### ISSUE TITLE
Currently deployed version of lab50.vsix errs if you try to close it via X icon

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#29]
<img width="585" alt="Screen Shot 2022-09-10 at 10 08 09 PM" src="https://user-images.githubusercontent.com/788678/189508790-3976b3f9-1a98-4413-9f8c-3317f4089a41.png">

Might be moot if production version is quite outdated now, though!

**Comment by rongxin-liu** [comment]
Will ship it through marketplace, easier to update.
