### ISSUE TITLE
When layout-panel-right icon is clicked, only re-lay out windows; update file(s) only when lab itself is opened

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#3]
That feels cleaner than cURLing files on every layout?

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/36d670d71930fb8fb5976c1f81d28794cb0a8b26](https://github.com/cs50/lab50.vsix/commit/36d670d71930fb8fb5976c1f81d28794cb0a8b26)
