### ISSUE TITLE
Should we add `chevron-right` to README pane that automatically maximizes width?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#32]
If it's possible for the primary sidebar to fill the width, covering the editor and terminal, just like the terminal's `chevron-up` icon fills the height, covering the editor?

And then `chevron-left` could shrink the primary sidebar back to normal size.

Might not be possible, though, or compelling.

Cf. https://code.visualstudio.com/api/references/icons-in-labels

**Comment by rongxin-liu** [comment]
Primary Side Bar cannot be maximized and we also cannot control its layout/width programmatically.

Related issue: #24
