### ISSUE TITLE
Only show "Open in CS50 Lab" if `README.md` has YAML front matter

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#35]
Else error appears when a front matter-less `README.md` is opened:

<img width="406" alt="Screen Shot 2022-09-11 at 1 50 34 PM" src="https://user-images.githubusercontent.com/788678/189541881-0d3190fd-dff4-48dd-a4e5-cf98b21a50a2.png">

**Comment by rongxin-liu** [comment]
What is this README looks like?

**Comment by dmalan** [comment]
Initially just:

```
---
---

# Caesar
...
```

Though for this particular one, will also add some explicit keys.

**Comment by rongxin-liu** [comment]
If this is achievable:

1. Our extension would need to find/read a "README.md" file whenever a user right-click a folder.
2. And need to intercept or disable the menu item in-time before the menu is shown.

**Comment by dmalan** [comment]
Hm, tricky, guessing the API might not even allow for (2), since it could slow down the opening of the context menu? Aok to leave as is, I'm thinking!
