### ISSUE TITLE
Incorrect HTTP status code when `url` doesn't exist on server

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#39]
<img width="553" alt="Screen Shot 2022-09-11 at 2 00 18 PM" src="https://user-images.githubusercontent.com/788678/189542249-30d688ad-8b43-4ad6-ba10-667b67dab375.png">

(Should be 404 in this case.)

**Comment by rongxin-liu** [comment]
This is not an HTTP status code, but exit code from `curl`.

**Comment by dmalan** [comment]
Possible to show HTTP status code instead? More useful to authors?
