### ISSUE TITLE
Change icon in activity bar to `book`

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#4]
* book
* ~folder-library~
* ~layout-sidebar-left~
* ~library~
* ~beaker~

Cf. https://code.visualstudio.com/api/references/icons-in-labels

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/904f01e958a101f851f1d87cb76864da6c1f0741](https://github.com/cs50/lab50.vsix/commit/904f01e958a101f851f1d87cb76864da6c1f0741)

**Comment by dmalan** [comment]
I realized that the `test-view-icon` appears in the activity bar automatically if you open a `.py` file, which might get confusing, especially for CS50P. :\
