### ISSUE TITLE
If a lab folder is opened in VS Code as a workspace folder, can't right-click the folder to open it as a lab

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#44]
For instance, in the below, I opened the lab folder as my workspace:

<img width="377" alt="Screen Shot 2022-09-11 at 1 49 55 PM" src="https://user-images.githubusercontent.com/788678/189543547-0a8b30e8-7d3d-4536-b73b-e64e8630a660.png">

Is it possible to enable right-clicking on the workspace folder in cases like this? If not, https://github.com/cs50/lab50.vsix/issues/45 is probably cleanest solution?

**Comment by rongxin-liu** [comment]
You can right-click the file explorer itself to "Open in CS50 Lab".

**Comment by dmalan** [comment]
Oh interesting!
