### ISSUE TITLE
Can markdown-it (or a markdown-it plugin) autolink URLs wrapped in angle brackets?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#51]
Just like Kramdown, whereby `<http://example.com/>` is interpreted as being the same as [http://example.com/](http://example.com/).

**Comment by rongxin-liu** [comment]
It appears to be the case already.

<img width="592" alt="Screen Shot 2022-09-11 at 22 19 16" src="https://user-images.githubusercontent.com/10591665/189562531-1bd11d3a-2dce-4829-9a37-6a520435481a.png">
