### ISSUE TITLE
Could extension detect when running in VS Code desktop and render YouTube videos as links instead of iframes?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#57]

**Comment by dmalan** [comment]
Awesome, thanks! Just to make the UX a bit closer to Codespaces, should we perhaps embed an `img` instead with the video's thumbnail, https://stackoverflow.com/a/2068371, at a 16x9 aspect ratio? And when clicked, the image leads to the URL? We could additional overlay a "play" icon perhaps as a call to action?

**Comment by rongxin-liu** [comment]
This is how how the video tag would be rendered on VS Code locally:

<img width="589" alt="Screen Shot 2022-09-28 at 09 35 27" src="https://user-images.githubusercontent.com/10591665/192793869-e961e464-10f5-434d-b85d-b5cafe78f363.png">

**Comment by dmalan** [comment]
Is it possible to mimic YouTube's play icon identically, as by using the same `img`?

**Comment by rongxin-liu** [comment]
Yes we can:

<img width="457" alt="Screen Shot 2022-09-28 at 10 17 27" src="https://user-images.githubusercontent.com/10591665/192803303-d79f55e1-6afb-49bf-b2fd-d1d1dd2d6a90.png">
