### ISSUE TITLE
If you close terminal (via ctrl-D), then click Reset Layout button in README, two terminals open

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#58]
<img width="171" alt="Screen Shot 2022-10-07 at 7 50 40 AM" src="https://user-images.githubusercontent.com/788678/194546657-a1c56789-fbd5-46b5-ac9b-f33327d3275f.png">

**Comment by rongxin-liu** [comment]
Hmm, it shouldn't be. I tried doing the same thing many times but only 1 terminal opened for me.

**Comment by dmalan** [comment]
Try closing the terminal with ctrl-D? Consistently results in 2 `bash` processes appearing for me when the Reset Layout button is then clicked.

**Comment by rongxin-liu** [comment]
Interesting. Pressing "X" is not behaving the same as pressing "Ctrl-D".
