### ISSUE TITLE
`README.md` no longer opens in lab when clicked in Explorer

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#59]
![image](https://user-images.githubusercontent.com/788678/194547188-77125fda-6346-4ee5-9e05-5156f32a4466.png)

<img width="1344" alt="Screen Shot 2022-10-07 at 7 53 46 AM" src="https://user-images.githubusercontent.com/788678/194547206-7b4b2b1e-9dfb-4a91-a41b-bb5ac18c2d81.png">

**Comment by rongxin-liu** [comment]
Haven't deployed the changes yet!
