### ISSUE TITLE
When README is closed via X icon, could we close all tabs and terminals, and open a new single terminal in /workspaces/{id}?

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#6]

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/278084ff3a97874634c1df6be0689b26a19e7e33](https://github.com/cs50/lab50.vsix/commit/278084ff3a97874634c1df6be0689b26a19e7e33)
