### ISSUE TITLE
Where is the source for the old lab editor?

### ISSUE THREAD

**Issue by bakerfugu** [cs50/lab50.vsix#61]
Hi! I'm an educator and I'm interested in making an open source project that uses a simple editor with some instructions, and I've been searching the cs50 organization for the source code for the old lab editor that looks like this:

![image](https://user-images.githubusercontent.com/7607483/261411809-51caaa80-39bb-4542-a931-7e9b58097f23.png)

This repo seems to contain some of the relevant code: https://github.com/cs50/lab50.vsix/blob/59c0f7695d40ca16e6eb1d8dfe43190713d7a26c/src/engine.ts

And I've found [some documentation which says that the old lab editor is being decommissioned](https://cs50.readthedocs.io/lab/). But there's no link to the source code for it.

Can you point me in the right direction? I'm really just looking for the source for the front end stuff, that renders the different panels.

**Comment by rongxin-liu** [comment]
Hi @bakerfugu , you might want to look at this repository:
https://github.com/cs50/sandbox.cs50.io

**Comment by bakerfugu** [comment]
I think that repo either doesn't exist or it's not publicly accessible?

![Screenshot_20230817_183810_GitHub.jpg](https://github.com/cs50/lab50.vsix/assets/7607483/383886a2-3af3-4d5f-b657-6fb83ab83928)

Similarly, this repo doesn't seem to have much front end source either:
https://github.com/cs50/sandbox

**Comment by rongxin-liu** [comment]
Sorry, this is the lab samples:
https://github.com/cs50/labs

If you are looking for the front end code of lab.cs50.io, I’m afraid those are not publicly available.
