### ISSUE TITLE
When user opens lab, close all tabs and terminals, then open required tabs and 1 terminal

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#7]

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/55af062e8a7c37d25f012b02d8545f12dd29018a](https://github.com/cs50/lab50.vsix/commit/55af062e8a7c37d25f012b02d8545f12dd29018a)

**Comment by dmalan** [comment]
PS what will happen if there's a running process in one of the terminals?

**Comment by rongxin-liu** [comment]
That process would presumably be killed. We are calling VS Code's API to dispose terminal so VS Code would take care of that.
