### ISSUE TITLE
Change "Open Problem Set" to "Open in CS50 Lab"

### ISSUE THREAD

**Issue by dmalan** [cs50/lab50.vsix#9]
Is it possible to put it under **Open in Integrated Terminal**, perhaps with a divider between that and it?

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/5304881f92327c12d5379a7b136a00ca79e1be04](https://github.com/cs50/lab50.vsix/commit/5304881f92327c12d5379a7b136a00ca79e1be04)

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/lab50.vsix/commit/f887a94b9c4fb1eca0e7703a0c2295f9ed36a9f3](https://github.com/cs50/lab50.vsix/commit/f887a94b9c4fb1eca0e7703a0c2295f9ed36a9f3)
